version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.2.24"
    restart: always
    ports:
      - "27017:27017"
  seed:
    build: ./seed
    depends_on:
      - mongodb